
#productName: JeeSite Files

#======================================#
#========= FileUpload settings ========#
#======================================#

# 文件服务
file:
  enabled: true

  # 关闭客户端服务，使用自身的文件服务
  client:
    enabled: false

  # 文件上传根路径，设置路径中不允许包含“userfiles”，在指定目录中系统会自动创建userfiles目录，如果不设置默认为contextPath路径
#  baseDir: D:/jeesite

#======================================#
#========== Project settings ==========#
#======================================#
    